sudo: required

language: go

services:
- docker

before_install:
- docker build -t melan/gen-events .
- docker run melan/gen-events --help

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master